CREATE TABLE medicine_details (
  MED_DETAILS_ID NUMBER(6,0) NOT NULL,
  MED_ID NUMBER(6,0) NOT NULL,
  COMPANY_NAME VARCHAR2(50),
  DISEASE_TREATED VARCHAR2(100),
  GENERIC_TYPE VARCHAR2(50), 
  CONSTRAINT medicine_details_pk PRIMARY KEY (MED_DETAILS_ID),
  CONSTRAINT medicine_details_fk_medicines FOREIGN KEY (MED_ID) REFERENCES medicines(MEDICINE_ID)
);
commit;